Module6 task2
htmlacademy-nodejs/1329823-buy-and-sell-3 pull request #18
Opened 2020-09-14 10:53 UTC by Liz-Che

2020-09-18 20:03 UTC, dean992008 requested changes
Не получаеться запустить приложение, падает из-за отсуствия файла.

2020-09-18 20:03 UTC, dean992008 commented on src/service/data-service/offer.js
> +const { offersToCategories } = require("../../../db/fill-db");
У меня при запуске падает приложение. Нет это JS файла для импорта.

2020-09-18 20:03 UTC, dean992008 commented on src/service/data-service/offer.js
> +const {Offer, Comment, Category, User, OffersToCategory} = sequelize.models;
OffersToCategory импортируеться, но не используеться. Нужно удалить.

2020-10-04 19:20 UTC, tsapko3628 commented on src/service/api/api-server.js
> +          new CategoryService()
странно, что один и тот же сервис инстанциируется дважды

2020-10-04 19:21 UTC, merged